Update to get the hello-world script run
- Line 20 "const Converter = require('@iota/converter');" was missing. So without it runs into the following failure:

const messageInTrytes = Converter.asciiToTrytes(message);
                        ^
ReferenceError: Converter is not defined
    at Object.<anonymous> (D:\...\iota-tutorial\index.js:18:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

- Line 82 changend "Iota" -> "iota" because it's defined in lower case on line 7. Otherwise it runs into the following failure:

Iota.prepareTransfers(seed, transfers)
         ^
TypeError: Iota.prepareTransfers is not a function
    at Object.<anonymous> (D:\...\iota-tutorial\index.js:29:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47